### ISSUE TITLE
[OID4VCI] vc.id is not in URI form.

### ISSUE THREAD

**Issue by t-kanuma** [hyperledger/aries-acapy-plugins#101]
When attempting to issue a JWT-VC to OWF Credo as a Holder, I received the following VC. You can see that the vc.id is not in URI form. Consequently, I encountered a validation error during issuance on Credo, which indicated that the VC is not compatible with the W3C VC Data Model.

https://www.w3.org/TR/vc-data-model/#identifiers
> The value of the id [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be a single [URI]

```json
{
  "vc":{
    "@context":[
      "https://www.w3.org/2018/credentials/v1"
    ],
    "type":[
      "VerifiableCredential",
      "PermanentResidentCredential"
    ],
    "id":"05d03459-65ca-45c4-812e-02a221d308a1",
    "issuer":"did:web:dijx0shbtuy59.cloudfront.net#key-1",
    "issuanceDate":"2024-01-29T07:23:30Z",
    "credentialSubject":{
      "givenName":"Taro",
      "familyName":"Yamada",
      "gender":"Male",
      "birthCountry":"Japan",
      "birthDate":"2020-01-01",
      "id":"did:key:z6Mkt4tyNA65DrACnSk45byGTZYpXag2soZMBqD1mVKEMQJW#z6Mkt4tyNA65DrACnSk45byGTZYpXag2soZMBqD1mVKEMQJW"
    }
  },
  "iss":"did:web:dijx0shbtuy59.cloudfront.net#key-1",
  "nbf":1706513010,
  "jti":"05d03459-65ca-45c4-812e-02a221d308a1",
  "sub":"did:key:z6Mkt4tyNA65DrACnSk45byGTZYpXag2soZMBqD1mVKEMQJW#z6Mkt4tyNA65DrACnSk45byGTZYpXag2soZMBqD1mVKEMQJW"
}
```

**Comment by PatStLouis** [comment]
the ID looks like a generated uuid, prepending this string with `urn:uuid:` should do the trick. There also seems to be missing context in this example. I think the [citizenship context](https://w3id.org/citizenship/v2) would work for this `PermanentResidentCredential` or include a `@vocab` object for issuer specific terms.

**Comment by dbluhm** [comment]
This should be fixed now.
