### ISSUE TITLE
Release and Publishing Strategy - Design Proposal

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-acapy-plugins#303]
The [hyperledger/aries-acapy-plugins](https://github.com/hyperledger/aries-acapy-plugins) repo contains a collection of plugins that are independently maintained.  As such each plugin is expected to evolve at it's own pace independently of the rest of the plugins.  This means the release and publish strategy for the repository and plugins needs to empower this independence by facilitating and allowing each plugin to have it's own flexible release cycle.

[hyperledger/indy-cli-rs](https://github.com/hyperledger/indy-cli-rs) utilizes an interesting [release](https://github.com/hyperledger/indy-cli-rs/blob/main/.github/workflows/release.yml) strategy triggered by an update to the code's version.  This same approach could be applied and expanded to support the independent release of each plugin.  Updating a plugin's version would trigger the process, checking whether a release for that plugin's version exists and if not, building and publishing a corresponding release of the associated plugin.  The releases would be identified by the plugin's name and the version of the release, and the tags would be formatted to clearly identify the plugin and version marked for a given release.  Additional logic could easily be build in to support RC releases based on the plugin's version being updated to an RC version.

**Comment by WadeBarnes** [comment]
cc @swcurran, @jamshale, @esune, For discussion.

**Comment by jamshale** [comment]
Going to close this. If we decide to do something for publishing or warnings in aca-py we can open another ticket.
