### ISSUE TITLE
Github workflow for validating a new ACA-Py release

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-acapy-plugins#36]
I think one of the key benefits we get from collecting plugins in this repo is validating each plugin against new releases of ACA-Py. This goes both ways: we get feedback on the ACA-Py release and we get early warning of compatibility issues or breaking changes in the plugins (assuming we run tests on pre-releases/release candidates).

I'm not sure the best way to accomplish this but I think it should be done! Thoughts?

**Comment by dbluhm** [comment]
If we do this the right way (and the integration tests for each of the plugins are constructed well), this effectively becomes another batch of integration tests for ACA-Py. I really like this lol. I'm always eager to have automated ways to increase our confidence in a release and detect issues early.

**Comment by jamshale** [comment]
The repo manager script is pretty stable now and could help with this workflow. If the workflow could detect that there was a new release of acapy, run the updater script and then then integration tests that would be great.

**Comment by jamshale** [comment]
I think this is basically being done and I am going to close this. There is potential to have more and better testing against aca-py in this repo. But I think any future tickets should more more specific and have more detailed descriptions.
