### ISSUE TITLE
[OID4VCI] Verification with Sphereon on iOS no longer works

### ISSUE THREAD

**Issue by robmuth** [hyperledger/aries-acapy-plugins#415]
A few weeks ago, I was able to issue demo credentials with the OID4VCI plugin and verify them with the Sphereon iOS wallet app. Unfortunately, the verification with the app stopped working and now fails with the error "The credential verification resulted in an error".

Can someone please check if it's just me or if the demo no longer works with the current Sphereon iOS app? Thanks in advance!

**Comment by dbluhm** [comment]
I believe we have identified the issue with issuing to Sphereon. We expect a fix to be published soon.

**Comment by jamshale** [comment]
I believe this should be fixed with the recent work on the plugin and demo. Closing... Please re-open if that's not the case.
