### ISSUE TITLE
Setup account to support automating PRs and Releases

### ISSUE THREAD

**Issue by WadeBarnes** [hyperledger/aries-acapy-plugins#458]
We'd like to automate the creation of PRs and Releases within this repository.  There have been a few attempts at configuring the permissions on the GitHub token account, but that did not seem to have the desired results.  @jamshale can provide some additional details.

We figure we need a Bot Account such as [Sovbot](https://github.com/sovbot) that has permissions to generate PRs and Releases on a repository.  This account is setup on the Indy repos (via the `indy-ci` team) and has permissions to create PRs and Releases in the Indy repos, [indy-node](https://github.com/hyperledger/indy-node) for example.

https://github.com/hyperledger/indy-node/blob/5dfb13075ddc1ce216385e170103141c010031d7/.github/workflows/tag.yaml#L70-L82

https://github.com/hyperledger/indy-node/blob/5dfb13075ddc1ce216385e170103141c010031d7/.github/workflows/publishRelease.yaml#L96-L107

**Comment by WadeBarnes** [comment]
@jamshale, Can you add some detail about the permissions you're already tried?

@ryjones, Here is the ticket as discussed yesterday.

**Comment by WadeBarnes** [comment]
Resources from @ryjones.  Setting permissions on the `GITHUB_TOKEN` that is created that allows PR creation.

Under Settings - Actions:
![image](https://github.com/hyperledger/aries-acapy-plugins/assets/10504350/73bc50cb-d386-4ffb-8900-0207ad1b6fcc)

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository

@jamshale, Please confirm this is what's already been tried.

**Comment by jamshale** [comment]
I'll check the permissions I needed on my forked branch for both workflows.

**Comment by jamshale** [comment]
@WadeBarnes So I'm pretty sure that the GITHUB_TOKEN with `allow github actions to create pull requests` would work for the first workflow. All it does is create the release PR. However, the second workflow which actually creates the release after the PR is merged would need a BOT type PAT token like the sov bot https://github.com/sovbot has. 

In a lot of ways the plugin workflows are the same as the indy-node workflows https://github.com/hyperledger/indy-node/blob/main/.github/workflows/publishRelease.yaml and will need similar permissions.

**Comment by WadeBarnes** [comment]
@ryjones, Is there a `Hyperledger` bot that can be used for such tasks?

**Comment by ryjones** [comment]
@WadeBarnes @jamshale I've set up `BOT_PR_PAT` as a fine-grained PAT with access to this repo. If it doesn't have enough beans to do the thing, let me know. I didn't give it every single permission - you should only use it in cases where `GITHUB_TOKEN` won't work.

**Comment by WadeBarnes** [comment]
Thanks @ryjones !
