### ISSUE TITLE
[OID4VCI] Testing the plugin with Paradym and Sphereon wallet fails

### ISSUE THREAD

**Issue by timbl-ont** [hyperledger/aries-acapy-plugins#463]
There are two issues that I found:

1. The Paradym wallets requires a URI for the ID and JTI i.e urn:uuid:xxxxxx. I could not find where this requirement is documented - perhaps an EU convention. This is a quick fix.

2. Validation checks fail in matching the kid, iss and controller for did:key.  There is a comment in the credo source code noting that # is not handled in the validation. This is more likely a fix for credo, but noting it here. The modified error message:

`
LOG kid 'did:key:z6MkoGLkQZttTBhvATLDKVU2tMxN8nVnLef7MVRp8DMqV5ab#z6MkoGLkQZttTBhvATLDKVU2tMxN8nVnLef7MVRp8DMqV5ab' does not match id of signer (holder/issuer) 'did:key:z6MkoGLkQZttTBhvATLDKVU2tMxN8nVnLef7MVRp8DMqV5ab#z6MkoGLkQZttTBhvATLDKVU2tMxN8nVnLef7MVRp8DMqV5ab' and documentID 'did:key:z6MkoGLkQZttTBhvATLDKVU2tMxN8nVnLef7MVRp8DMqV5ab'`

`
 LOG  Verification method controller 'did:key:z6MkoGLkQZttTBhvATLDKVU2tMxN8nVnLef7MVRp8DMqV5ab' does not match the signer 'did:key:z6MkoGLkQZttTBhvATLDKVU2tMxN8nVnLef7MVRp8DMqV5ab#z6MkoGLkQZttTBhvATLDKVU2tMxN8nVnLef7MVRp8DMqV5ab'`

Issuance of a JWT VC to the Paradym wallet was successful after modifying the validation code in the wallet and fixing the URI in the plugin.  I was not able to compile the Sphereon wallet, but it may have the same logic. FYI @dbluhm

**Comment by dbluhm** [comment]
This should be fixed now; we're able to issue to paradym and sphereon now.
