### ISSUE TITLE
Problems with extending integration tests.

### ISSUE THREAD

**Issue by jamshale** [hyperledger/aries-acapy-plugins#50]
@Jsyro Was adding a basic endpoint to the `basic_message` plugin for deleting messages, and when attempting to add an integration test he was experiencing the agents getting a `ProfileSessionNotActive` error when triggering the endpoint. This is despite the endpoint working correctly with manual testing, and sending basic messages to each other, getting the messages with the api working correctly.

I saw this behaviour before but I'm not sure what's going on. Need to investigate and find a solution to be able to easily extend integration tests.

**Comment by Jsyro** [comment]
Indentation matters, the issue i ran into was expected, I was calling the `session` outside of the `with` block. 

User Error...
