### ISSUE TITLE
redis_events does not deliver webhooks

### ISSUE THREAD

**Issue by jpnorthernblock** [hyperledger/aries-acapy-plugins#82]
Given I configure an ACA-Py (v. 0.10.3) agent with the redis_events plugin (v. 0.1.0) 

Given I have following ACA-Py configuration : 

```
auto-provision: true

admin: [0.0.0.0, 3001]
admin-insecure-mode: true

inbound-transport:
  - [redis_events.v1_0.redis_queue.inbound, redis, 0]
outbound-transport: redis_events.v1_0.redis_queue.outbound
endpoint:
  - http://relay:8071

plugin:
  - redis_events.v1_0.redis_queue.events
plugin-config: plugins-config.yml

no-ledger: true

debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true
auto-respond-messages: true
```

Given I have following plugin configuration : 

```
redis_queue:
  connection:
    connection_url: "redis://default:test1234@172.28.0.103:6379"

  inbound:
    acapy_inbound_topic: "acapy_inbound"
    acapy_direct_resp_topic: "acapy_inbound_direct_resp"

  outbound:
    acapy_outbound_topic: "acapy_outbound"
    mediator_mode: false

  event:
    event_topic_maps:
      ^acapy::webhook::(.*)$: acapy-webhook-$wallet_id
      ^acapy::record::([^:]*)::([^:]*)$: acapy-record-with-state-$wallet_id
      ^acapy::record::([^:])?: acapy-record-$wallet_id
      acapy::basicmessage::received: acapy-basicmessage-received
      acapy::problem_report: acapy-problem_report
      acapy::ping::received: acapy-ping-received
      acapy::ping::response_received: acapy-ping-response_received
      acapy::actionmenu::received: acapy-actionmenu-received
      acapy::actionmenu::get-active-menu: acapy-actionmenu-get-active-menu
      acapy::actionmenu::perform-menu-action: acapy-actionmenu-perform-menu-action
      acapy::keylist::updated: acapy-keylist-updated
      acapy::revocation-notification::received: acapy-revocation-notification-received
      acapy::revocation-notification-v2::received: acapy-revocation-notification-v2-received
      acapy::forward::received: acapy-forward-received
    event_webhook_topic_maps:
      acapy::basicmessage::received: basicmessages
      acapy::problem_report: problem_report
      acapy::ping::received: ping
      acapy::ping::response_received: ping
      acapy::actionmenu::received: actionmenu
      acapy::actionmenu::get-active-menu: get-active-menu
      acapy::actionmenu::perform-menu-action: perform-menu-action
      acapy::keylist::updated: keylist
    deliver_webhook: true
```

Given I start the ACA-Py agent with a --webhook-url parameter pointing to a runnnig mock server. 

When the agent accepts a connection request and sends a connection response

Then I do see the webhook messages in redis in the acapy_outbound list (with configured url + '/topic/None' as topic)
Then webhooks are never delivered to the endpoint (the mock server).
Then connection response is never sent and connection stalls in a 'response' state (vs state': 'completed'). 

Expected : Endpoint does receive webhook post requests (that have a real '/topic/' defined in url and not '/topic/None') AND connection is correctly established.

Note : I did confirm that with this same exact setup, if plugin is not loaded, endpoint does receive webhook post requests with correct topics defined and connection is correctly established  (state': 'completed').

Note : I also did confirm that with this same exact setup, if plugin IS loaded but there is no --webhook-url start argument passed to ACA-Py, then connection is correctly established (state': 'completed')

**Comment by jamshale** [comment]
Ok. I can replicate the issue. I'm not sure if having the webhook url forwarding was ever considered. It wasn't tested with the current setup.

It should be supported though, that's for sure. I'll work on fixing it.

**Comment by jamshale** [comment]
I could replicate the issue but I'm pretty sure this is a configuration issue. Although the documentation and sample plugin-config should be better.

The default webhook event map is in `redis_events/v1_0/redis_queue/config.py` and is:

> EVENT_WEBHOOK_TOPIC_MAP = {
    "acapy::basicmessage::received": "basicmessages",
    "acapy::problem_report": "problem_report",
    "acapy::ping::received": "ping",
    "acapy::ping::response_received": "ping",
    "acapy::actionmenu::received": "actionmenu",
    "acapy::actionmenu::get-active-menu": "get-active-menu",
    "acapy::actionmenu::perform-menu-action": "perform-menu-action",
    "acapy::keylist::updated": "keylist",
}

But this actually misses a lot of events, hence getting the `None` topics.

The plugin-config file actually needs a `event_webhook_topic_maps` section to customize it.

```yml
  ### For Event ###
  event:
    event_topic_maps:
      ^acapy::webhook::(.*)$: acapy-webhook-$wallet_id
      ^acapy::record::([^:]*)::([^:]*)$: acapy-record-with-state-$wallet_id
      ^acapy::record::([^:])?: acapy-record-$wallet_id
      acapy::basicmessage::received: acapy-basicmessage-received
      acapy::problem_report: acapy-problem_report
      acapy::ping::received: acapy-ping-received
      acapy::ping::response_received: acapy-ping-response_received
      acapy::actionmenu::received: acapy-actionmenu-received
      acapy::actionmenu::get-active-menu: acapy-actionmenu-get-active-menu
      acapy::actionmenu::perform-menu-action: acapy-actionmenu-perform-menu-action
      acapy::keylist::updated: acapy-keylist-updated
      acapy::revocation-notification::received: acapy-revocation-notification-received
      acapy::revocation-notification-v2::received: acapy-revocation-notification-v2-received
      acapy::forward::received: acapy-forward-received
    event_webhook_topic_maps:
      acapy::basicmessage::received: basicmessages
      acapy::problem_report: problem_report
      acapy::ping::received: ping
      acapy::ping::response_received: ping
      acapy::actionmenu::received: actionmenu
      acapy::actionmenu::get-active-menu: get-active-menu
      acapy::actionmenu::perform-menu-action: perform-menu-action
      acapy::keylist::updated: keylist
      acapy::record::connections::response: acapy-record-connections-response
      acapy::record::connections::request: acapy-record-connections-request
      acapy::record::connections::invitation: acapy-record-connections-invitation
      acapy::record::connections::active: acapy-record-connections-active
    deliver_webhook: true
```

This config stops the `None` topic types in the integration tests.

I'm going to improve the documentation and plugin-config sample but I'm pretty confident it is working correctly.

**Comment by jpnorthernblock** [comment]
Thank you for the investigation and update.

I tried this updated event_webhook_topic_maps and indeed, the topics are now (mostly) defined (I still have 4 /topic/None entries in acapy_outbound, before it was 8 or 9). BUT ... messages are still stuck in acapy_outbound and still not delivered. Furthermore, this still stops the connexion response message from beeing sent to the second agent.

**Comment by jpnorthernblock** [comment]
Could the deliverer not deliver those messages anyway (even if topic is topic/None) ? Its a message with an url and a payload, like any other messages and the url is reachable. Of course the controler would not know what to do with those /topic/None but at least messages would not get stuck in acapy_outbound.

Or even more generaly, why can one single message stuck in acapy_outbound keep the deliverer from delivering all following messages ? Is there an intention behind this ? It seems to be a single point of failure where as soon as some message cannot be delivered (no matter the reason), all following messages get stuck forever in acapy_outbound.

**Comment by jamshale** [comment]
I'm trying to look into what your saying. I didn't design this so I'm not sure.

It shouldn't be queuing messages when it doesn't match a topic. I was going to fix that.

**Comment by jpnorthernblock** [comment]
Thanks! The reason I bring up this idea that a single message stuck in acapy_outbound should probably not prevent any following messages from beeing delivered is that I've seen, in my tests, other contexts absolutely not related to the webhooks, where a message  not beeing delivered forced other following messages to stay indefinitely stuck. It happened when I did weird and unnatural changes to the configurations and set-up without resetting redis data but still, it crippled the outbound queue. This most probably should be considered as an issue all by itself though.

**Comment by jamshale** [comment]
I understand the problem better now. It seems like it has something to do with not handling bad responses from and available web hook server. I'll try and sort it out. Thanks for your help.

**Comment by jamshale** [comment]
@jpnorthernblock  https://github.com/hyperledger/aries-acapy-plugins/pull/86. Can't add you as a reviewer.

**Comment by jpnorthernblock** [comment]
@jamshale Works for me with current scenario! With PR #86 the web-hooks are pushed to the redis outbound queue with right topic and delivered correctly. 

I'll be playing around with the plugin in the days to come to see if I can still reproduce the "message stuck in outbound queue" problem in any other way, and if I do, it'll be a different issue.

Big thank you!
