### ISSUE TITLE
Devcontainers should include Poetry version 1.6.1 (or 1.7.1?)

### ISSUE THREAD

**Issue by loneil** [hyperledger/aries-acapy-plugins#84]
The ACA-Py libraries are built with 1.6.1
https://github.com/hyperledger/aries-cloudagent-python/blob/main/poetry.lock

so probably want to stay in sync for this repo's Poetry usage in the devcontainer? Currently `"POETRY_VERSION": "1.4.2"`
https://github.com/hyperledger/aries-acapy-plugins/tree/main/plugin_globals/.devcontainer

**Comment by loneil** [comment]
Each individual plugin seems to have been generated on 1.7.1 though. But the devcontainer definitions say 1.4.2 as well

**Comment by jamshale** [comment]
I ran the script locally that's why it's 1.7.1. Dev containers should be updated :heavy_check_mark:

**Comment by loneil** [comment]
Ok thanks. I did a PR to update them here. Found 1.4.2 references in dockerfiles too
https://github.com/hyperledger/aries-acapy-plugins/pull/85
