### ISSUE TITLE
Oid4vci Integration tests

### ISSUE THREAD

**Issue by jamshale** [hyperledger/aries-acapy-plugins#886]
The oid4vci integration tests started failing for an unknown reason in workflows and also locally. It's preventing library maintenance upgrades from being completed and will likely prevent this plugin from being upgraded with the ac-py 1.0.0 release.

See https://github.com/hyperledger/aries-acapy-plugins/actions/runs/10248337786/job/28349404749

@weiiv Would you be able to look at this. I'm not sure why they were passing before and started failing?

Tagging @dbluhm as well. I looked at them for a while, but I'm not familiar with this plugin right now and thought it would be better to see if the recent developers knew what was happening.

**Comment by dbluhm** [comment]
We'll look into this!

**Comment by dbluhm** [comment]
https://github.com/hyperledger/aries-acapy-plugins/commit/e73878e8543080c19b6665e36bdec9c005374ad1#diff-2e07db531d84982252930ae00ce597e6e2c9fabdb4450eadb19ff5e494de53abR31-R35

@jamshale These lines are necessary in the oid4vci integration tests to skip tests that only work with a tunnel (we don't want to worry about opening tunnels in github actions so these are intended to only be run locally). These lines were removed by:

https://github.com/hyperledger/aries-acapy-plugins/commit/baacaa3a96168e44371009a9230bbfc9a0a802d6

Is there a part of the automated release workflow that's clobbering the integration pyproject.toml?

**Comment by jamshale** [comment]
OK. Thanks for looking. I'll fix it. The workflow should allow these extra setting sections, but it must have not worked as intended. I'll add them back and check out the workflow.
